[package]
name = "rust-dyn-syst"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.0"
egui_graphs = "0.29.0"
egui_plot = "0.34.0"
petgraph = "0.8.3"
rand = "0.9.2"
serde = { version = "1.0", features = ["derive"] }
